### ISSUE TITLE
Schema enhancements, including to support SDG

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/impactoss-server#206]

**Comment by tmfrnz** [comment]
### New fields
**table "categories":**
- t.integer  "number"   

**table "indicators"**   
- t.string  "reference"

**table "pages"**
- t.integer "order"

**table "recommendations"**
- t.boolean  "accepted"
- t.text  "response"

**table "taxonomies"**
- t.integer  "priority"
- t.boolean  "tags_sdgtargets"
- t.boolean  "is_smart", default: false


### New tables

**table "sdgtarget_categories"**
- t.integer  "sdgtarget_id"
- t.integer  "category_id"
- t.datetime "created_at",  null: false
- t.datetime "updated_at",  null: false

**table "sdgtarget_indicators"**
- t.integer  "sdgtarget_id"
- t.integer  "indicator_id"
- t.datetime "created_at",   null: false
- t.datetime "updated_at",   null: false
- t.index ["sdgtarget_id"], name: "index_sdgtarget_indicators_on_sdgtarget_id", using: :btree
- t.index ["indicator_id"], name: "index_sdgtarget_indicators_on_indicator_id", using: :btree    

**table "sdgtargets"** 
- t.string  "reference",       null: false    
- t.string     "title",       null: false
- t.text     "description"
- t.datetime "created_at",                  null: false
- t.datetime "updated_at",                  null: false
- t.boolean  "draft",       default: false
- t.index ["draft"], name: "index_sdgtargets_on_draft", using: :btree

### Other tables that could be good to have in the future
  
**table "sdgtarget_measures"**
- t.integer  "sdgtarget_id"
- t.integer  "measure_id"
- t.datetime "created_at",   null: false
- t.datetime "updated_at",   null: false

**table "sdgtarget_recommendations"**
- t.integer  "sdgtarget_id"
- t.integer  "recommendation_id"
- t.datetime "created_at",   null: false
- t.datetime "updated_at",   null: false

**table "measure_indicators"**
- t.integer  "measure_id"
- t.integer  "indicator_id"
- t.datetime "created_at",   null: false
- t.datetime "updated_at",   null: false
- ADD??? t.index ["measure_id"], name: "index_measure_indicators_on_measure_id", using: :btree
- ADD??? t.index ["indicator_id"], name: "index_measure_indicators_on_indicator_id", using: :btree

**Comment by tmfrnz** [comment]
Further please change all "title" and "description" field types from string to text, most importantly for tables
- indicators
- recommendations

**Comment by tmfrnz** [comment]
Please also change the field type for number in table "recommendations" to string. The field name is confusing but we need to allow numbers such as 1.A.2

**Comment by barancw** [comment]
@tmfrnz, I added the category number to the serializer.  It's deployed to staging and production.

**Comment by tmfrnz** [comment]
@barancw thanks for adding the required sdg tables. only minor thing I notice is the missing explicit "required fields"  for the sdg-target table
>  t.string "reference", null: false
 t.text "title", null: false

**Comment by tmfrnz** [comment]
@barancw new indicator field 'reference' appears to be missing in policy - will try to add

**Comment by tmfrnz** [comment]
also most other new fields have yet to be added to policy

**Comment by barancw** [comment]
@tmfrnz The "reference" and "title" fields will be validated for presence here:

https://github.com/dumparkltd/hr-nmrf-server/blob/master/app/models/sdgtarget.rb#L4

**Comment by tmfrnz** [comment]
ok makes sense! thanks

**Comment by barancw** [comment]
@tmfrnz Is this done now, minus sdgtarget_measures and sdgtarget_recommendations?

**Comment by barancw** [comment]
@tmfrnz Just give this all a once over to make sure nothing was missed

**Comment by tmfrnz** [comment]
### table "categories":
It turns out that category references can also contain characters . To be consistent I would suggest to add a new field reference (string) and drop the newly created number field.

**Comment by tmfrnz** [comment]
### New fields
**table "measures":**
- [ ] t.outcome "text"
- [ ] t.indicator_summary "text"
- [ ] t.target_date_comment "text"
